// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSAM59LGet1vxpZLt9WN7TFFuB5yKn8To',
    appId: '1:735278945774:web:c7af09e9f9fb1eda50aaff',
    messagingSenderId: '735278945774',
    projectId: 'ciro-app-ceece',
    authDomain: 'ciro-app-ceece.firebaseapp.com',
    storageBucket: 'ciro-app-ceece.firebasestorage.app',
    measurementId: 'G-G9959WHY25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ep6Wyffv_y7RIEwPKpbiACPx3Ts51VA',
    appId: '1:735278945774:android:622e49b2f997dca150aaff',
    messagingSenderId: '735278945774',
    projectId: 'ciro-app-ceece',
    storageBucket: 'ciro-app-ceece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWQpRLZDesqpSM9tbPpkti1V0287EctdE',
    appId: '1:735278945774:ios:c6f57cf20214020150aaff',
    messagingSenderId: '735278945774',
    projectId: 'ciro-app-ceece',
    storageBucket: 'ciro-app-ceece.firebasestorage.app',
    iosBundleId: 'com.example.ciroChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWQpRLZDesqpSM9tbPpkti1V0287EctdE',
    appId: '1:735278945774:ios:c6f57cf20214020150aaff',
    messagingSenderId: '735278945774',
    projectId: 'ciro-app-ceece',
    storageBucket: 'ciro-app-ceece.firebasestorage.app',
    iosBundleId: 'com.example.ciroChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSAM59LGet1vxpZLt9WN7TFFuB5yKn8To',
    appId: '1:735278945774:web:571e6797514c12fb50aaff',
    messagingSenderId: '735278945774',
    projectId: 'ciro-app-ceece',
    authDomain: 'ciro-app-ceece.firebaseapp.com',
    storageBucket: 'ciro-app-ceece.firebasestorage.app',
    measurementId: 'G-0Q6EPRJ8Q6',
  );
}
